allowBuilds:
  '@compodoc/compodoc': true
  '@scarf/scarf': true
  aws-sdk: true
  bcrypt: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@eslint/eslintrc@3.3.6'
  - '@nestjs/cli@11.0.24'
  - eslint@10.7.0
